// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleSchool.Data;

#nullable disable

namespace SimpleSchool.Migrations
{
    [DbContext(typeof(SimpleSchoolContext))]
    [Migration("20250523124243_rollen veranderd")]
    partial class rollenveranderd
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OpleidingVak", b =>
                {
                    b.Property<int>("OpleidingenId")
                        .HasColumnType("int");

                    b.Property<int>("VakkenId")
                        .HasColumnType("int");

                    b.HasKey("OpleidingenId", "VakkenId");

                    b.HasIndex("VakkenId");

                    b.ToTable("Opleidingsvakken", (string)null);
                });

            modelBuilder.Entity("SimpleSchool.Models.Leerkracht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Leerkracht");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Adres = "Noapark 5",
                            EMail = "et",
                            GeboorteDatum = new DateTime(2024, 10, 23, 22, 32, 14, 287, DateTimeKind.Local).AddTicks(5054),
                            Naam = "Jayden Bruin"
                        },
                        new
                        {
                            Id = 12,
                            Adres = "Brouwersteeg 566 I",
                            EMail = "dolorem",
                            GeboorteDatum = new DateTime(2024, 6, 13, 22, 52, 46, 117, DateTimeKind.Local).AddTicks(6597),
                            Naam = "Johannes Vermeulen"
                        },
                        new
                        {
                            Id = 13,
                            Adres = "Daanplantsoen 742a",
                            EMail = "soluta",
                            GeboorteDatum = new DateTime(2024, 11, 22, 10, 33, 9, 785, DateTimeKind.Local).AddTicks(2640),
                            Naam = "Maud Wit"
                        },
                        new
                        {
                            Id = 14,
                            Adres = "Petersplein 394c",
                            EMail = "voluptatem",
                            GeboorteDatum = new DateTime(2024, 11, 1, 2, 46, 50, 225, DateTimeKind.Local).AddTicks(9819),
                            Naam = "Julian Bakker"
                        },
                        new
                        {
                            Id = 15,
                            Adres = "Femkepassage 655a",
                            EMail = "dolor",
                            GeboorteDatum = new DateTime(2024, 8, 26, 4, 10, 37, 408, DateTimeKind.Local).AddTicks(9085),
                            Naam = "Amber Schouten"
                        },
                        new
                        {
                            Id = 16,
                            Adres = "Boersloot 739a",
                            EMail = "vel",
                            GeboorteDatum = new DateTime(2024, 8, 26, 4, 54, 52, 224, DateTimeKind.Local).AddTicks(3315),
                            Naam = "Thijs Visser"
                        },
                        new
                        {
                            Id = 17,
                            Adres = "Brinkweg 0",
                            EMail = "et",
                            GeboorteDatum = new DateTime(2025, 2, 3, 11, 21, 56, 151, DateTimeKind.Local).AddTicks(6182),
                            Naam = "Bas Broek"
                        },
                        new
                        {
                            Id = 18,
                            Adres = "Kostergracht 749 II",
                            EMail = "consequatur",
                            GeboorteDatum = new DateTime(2024, 10, 21, 1, 47, 12, 588, DateTimeKind.Local).AddTicks(2990),
                            Naam = "Nick Smits"
                        },
                        new
                        {
                            Id = 19,
                            Adres = "Grootpassage 2",
                            EMail = "ipsam",
                            GeboorteDatum = new DateTime(2025, 4, 1, 19, 34, 16, 600, DateTimeKind.Local).AddTicks(1970),
                            Naam = "Bas Dekker"
                        },
                        new
                        {
                            Id = 20,
                            Adres = "Liekerijk 358b",
                            EMail = "ducimus",
                            GeboorteDatum = new DateTime(2024, 9, 13, 9, 8, 11, 691, DateTimeKind.Local).AddTicks(4926),
                            Naam = "Jasper Smits"
                        });
                });

            modelBuilder.Entity("SimpleSchool.Models.Leerling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("GeboorteDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OpleidingId")
                        .HasColumnType("int");

                    b.Property<int>("StudentenkaartId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OpleidingId");

                    b.HasIndex("StudentenkaartId")
                        .IsUnique();

                    b.ToTable("Leerling");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Adres = "Smitsplantsoen 223b",
                            EMail = "facere",
                            GeboorteDatum = new DateTime(2024, 9, 25, 2, 36, 34, 334, DateTimeKind.Local).AddTicks(3000),
                            Naam = "Tim Meer",
                            OpleidingId = 11,
                            StudentenkaartId = 11
                        },
                        new
                        {
                            Id = 12,
                            Adres = "Larsplantsoen 484 I",
                            EMail = "pariatur",
                            GeboorteDatum = new DateTime(2024, 10, 7, 3, 15, 30, 643, DateTimeKind.Local).AddTicks(3794),
                            Naam = "Sanne Graaf",
                            OpleidingId = 12,
                            StudentenkaartId = 12
                        },
                        new
                        {
                            Id = 13,
                            Adres = "Grootweg 950 III",
                            EMail = "magni",
                            GeboorteDatum = new DateTime(2024, 6, 28, 11, 12, 51, 334, DateTimeKind.Local).AddTicks(6522),
                            Naam = "Britt Hendriks",
                            OpleidingId = 13,
                            StudentenkaartId = 13
                        },
                        new
                        {
                            Id = 14,
                            Adres = "Bruinpark 030 I",
                            EMail = "est",
                            GeboorteDatum = new DateTime(2025, 4, 1, 1, 56, 6, 930, DateTimeKind.Local).AddTicks(4824),
                            Naam = "Julian Brouwer",
                            OpleidingId = 14,
                            StudentenkaartId = 14
                        },
                        new
                        {
                            Id = 15,
                            Adres = "Irispark 164 I",
                            EMail = "exercitationem",
                            GeboorteDatum = new DateTime(2025, 1, 16, 19, 25, 42, 534, DateTimeKind.Local).AddTicks(4215),
                            Naam = "Femke Ven",
                            OpleidingId = 15,
                            StudentenkaartId = 15
                        },
                        new
                        {
                            Id = 16,
                            Adres = "Julianmarkt 549 I",
                            EMail = "et",
                            GeboorteDatum = new DateTime(2025, 2, 13, 1, 59, 51, 693, DateTimeKind.Local).AddTicks(6817),
                            Naam = "Sven Meijer",
                            OpleidingId = 16,
                            StudentenkaartId = 16
                        },
                        new
                        {
                            Id = 17,
                            Adres = "Sanderstraat 8",
                            EMail = "tenetur",
                            GeboorteDatum = new DateTime(2024, 10, 4, 5, 17, 11, 727, DateTimeKind.Local).AddTicks(6109),
                            Naam = "Eva Peters",
                            OpleidingId = 17,
                            StudentenkaartId = 17
                        },
                        new
                        {
                            Id = 18,
                            Adres = "Meijerstraat 257",
                            EMail = "aut",
                            GeboorteDatum = new DateTime(2025, 3, 6, 20, 41, 5, 745, DateTimeKind.Local).AddTicks(9792),
                            Naam = "Thijs Broek",
                            OpleidingId = 18,
                            StudentenkaartId = 18
                        },
                        new
                        {
                            Id = 19,
                            Adres = "Mulderkade 644",
                            EMail = "ut",
                            GeboorteDatum = new DateTime(2024, 11, 20, 22, 1, 52, 989, DateTimeKind.Local).AddTicks(5471),
                            Naam = "Stijn Wit",
                            OpleidingId = 19,
                            StudentenkaartId = 19
                        },
                        new
                        {
                            Id = 20,
                            Adres = "Johannesrijk 071a",
                            EMail = "quia",
                            GeboorteDatum = new DateTime(2024, 9, 20, 16, 10, 16, 64, DateTimeKind.Local).AddTicks(4273),
                            Naam = "Bram Brink",
                            OpleidingId = 20,
                            StudentenkaartId = 20
                        });
                });

            modelBuilder.Entity("SimpleSchool.Models.Opleiding", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BeschikbarePlaatsen")
                        .HasColumnType("int");

                    b.Property<string>("Beschrijving")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duur")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Opleiding");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            BeschikbarePlaatsen = 332,
                            Beschrijving = "Voluptatum suscipit et vel tempore ea quae cum qui dignissimos.",
                            Duur = 4,
                            Naam = "Quis quisquam ratione."
                        },
                        new
                        {
                            Id = 12,
                            BeschikbarePlaatsen = 320,
                            Beschrijving = "Recusandae nihil aut non nihil expedita quisquam laborum qui quae.",
                            Duur = 4,
                            Naam = "Et saepe ut."
                        },
                        new
                        {
                            Id = 13,
                            BeschikbarePlaatsen = 384,
                            Beschrijving = "Ullam nobis occaecati eaque et omnis ullam est inventore a.",
                            Duur = 4,
                            Naam = "Nulla natus possimus."
                        },
                        new
                        {
                            Id = 14,
                            BeschikbarePlaatsen = 235,
                            Beschrijving = "Sed reprehenderit officiis pariatur illo hic est numquam aliquam consequatur.",
                            Duur = 4,
                            Naam = "Omnis beatae at."
                        },
                        new
                        {
                            Id = 15,
                            BeschikbarePlaatsen = 366,
                            Beschrijving = "Voluptas nostrum eos nam ratione rerum autem adipisci itaque quae.",
                            Duur = 4,
                            Naam = "Facere est quae."
                        },
                        new
                        {
                            Id = 16,
                            BeschikbarePlaatsen = 230,
                            Beschrijving = "Culpa accusamus nobis velit non blanditiis est voluptates atque ut.",
                            Duur = 4,
                            Naam = "Harum est illo."
                        },
                        new
                        {
                            Id = 17,
                            BeschikbarePlaatsen = 210,
                            Beschrijving = "Eum aliquam rerum incidunt fugit voluptatem itaque amet dolor tempora.",
                            Duur = 3,
                            Naam = "Est totam voluptatem."
                        },
                        new
                        {
                            Id = 18,
                            BeschikbarePlaatsen = 284,
                            Beschrijving = "Quia iste et odit nihil aut ipsa harum fugiat quis.",
                            Duur = 4,
                            Naam = "Maxime adipisci recusandae."
                        },
                        new
                        {
                            Id = 19,
                            BeschikbarePlaatsen = 291,
                            Beschrijving = "Deleniti aut nesciunt necessitatibus eius vel necessitatibus dolorem vero necessitatibus.",
                            Duur = 4,
                            Naam = "Sequi eum et."
                        },
                        new
                        {
                            Id = 20,
                            BeschikbarePlaatsen = 237,
                            Beschrijving = "Voluptatem facere odit veritatis quibusdam magni tempora nesciunt est ipsum.",
                            Duur = 3,
                            Naam = "Rerum nobis et."
                        });
                });

            modelBuilder.Entity("SimpleSchool.Models.StudentenKaart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Klas")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("School")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("StudentenKaart");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Klas = "totam",
                            Naam = "Ella Peters Sr.",
                            School = "Dekker, Broek and Heuvel"
                        },
                        new
                        {
                            Id = 12,
                            Klas = "in",
                            Naam = "Prof. Mare Janssen",
                            School = "Heuvel Group"
                        },
                        new
                        {
                            Id = 13,
                            Klas = "at",
                            Naam = "Leon Smits Sr.",
                            School = "Haan, Visser and Vries"
                        },
                        new
                        {
                            Id = 14,
                            Klas = "pariatur",
                            Naam = "Mevr. Dr. Medina Ven",
                            School = "Meer - Vries"
                        },
                        new
                        {
                            Id = 15,
                            Klas = "officiis",
                            Naam = "Dhr. Bob Jansen",
                            School = "Groot - Bakker"
                        },
                        new
                        {
                            Id = 16,
                            Klas = "itaque",
                            Naam = "Prof. Mert Dijk",
                            School = "Janssen - Heuvel"
                        },
                        new
                        {
                            Id = 17,
                            Klas = "nesciunt",
                            Naam = "Jackson Visser IV",
                            School = "Groot International"
                        },
                        new
                        {
                            Id = 18,
                            Klas = "sit",
                            Naam = "Dhr. Oumayra Boer",
                            School = "Koning N.V."
                        },
                        new
                        {
                            Id = 19,
                            Klas = "animi",
                            Naam = "Prof. Jenna Ruiter",
                            School = "Janssen, Schouten and Hendriks"
                        },
                        new
                        {
                            Id = 20,
                            Klas = "doloribus",
                            Naam = "Britt Heuvel Jr.",
                            School = "Maas - Janssen"
                        });
                });

            modelBuilder.Entity("SimpleSchool.Models.Vak", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AantalStudiePunten")
                        .HasColumnType("int");

                    b.Property<int>("LeerkrachtId")
                        .HasColumnType("int");

                    b.Property<string>("Naam")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Taal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Vaktype")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LeerkrachtId");

                    b.ToTable("Vak");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            AantalStudiePunten = 35,
                            LeerkrachtId = 11,
                            Naam = "repellendus",
                            Taal = "vero",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 12,
                            AantalStudiePunten = 46,
                            LeerkrachtId = 12,
                            Naam = "a",
                            Taal = "quos",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 13,
                            AantalStudiePunten = 40,
                            LeerkrachtId = 13,
                            Naam = "quia",
                            Taal = "aperiam",
                            Vaktype = 1
                        },
                        new
                        {
                            Id = 14,
                            AantalStudiePunten = 33,
                            LeerkrachtId = 14,
                            Naam = "quae",
                            Taal = "veniam",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 15,
                            AantalStudiePunten = 25,
                            LeerkrachtId = 15,
                            Naam = "minus",
                            Taal = "repellendus",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 16,
                            AantalStudiePunten = 15,
                            LeerkrachtId = 16,
                            Naam = "adipisci",
                            Taal = "est",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 17,
                            AantalStudiePunten = 26,
                            LeerkrachtId = 17,
                            Naam = "aut",
                            Taal = "officia",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 18,
                            AantalStudiePunten = 23,
                            LeerkrachtId = 18,
                            Naam = "eveniet",
                            Taal = "tenetur",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 19,
                            AantalStudiePunten = 39,
                            LeerkrachtId = 19,
                            Naam = "unde",
                            Taal = "possimus",
                            Vaktype = 0
                        },
                        new
                        {
                            Id = 20,
                            AantalStudiePunten = 49,
                            LeerkrachtId = 20,
                            Naam = "voluptas",
                            Taal = "aut",
                            Vaktype = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OpleidingVak", b =>
                {
                    b.HasOne("SimpleSchool.Models.Opleiding", null)
                        .WithMany()
                        .HasForeignKey("OpleidingenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleSchool.Models.Vak", null)
                        .WithMany()
                        .HasForeignKey("VakkenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SimpleSchool.Models.Leerling", b =>
                {
                    b.HasOne("SimpleSchool.Models.Opleiding", "Opleiding")
                        .WithMany("Leerlingen")
                        .HasForeignKey("OpleidingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SimpleSchool.Models.StudentenKaart", "Studentenkaart")
                        .WithOne("Leerling")
                        .HasForeignKey("SimpleSchool.Models.Leerling", "StudentenkaartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Opleiding");

                    b.Navigation("Studentenkaart");
                });

            modelBuilder.Entity("SimpleSchool.Models.Vak", b =>
                {
                    b.HasOne("SimpleSchool.Models.Leerkracht", "Leerkracht")
                        .WithMany("Vakken")
                        .HasForeignKey("LeerkrachtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Leerkracht");
                });

            modelBuilder.Entity("SimpleSchool.Models.Leerkracht", b =>
                {
                    b.Navigation("Vakken");
                });

            modelBuilder.Entity("SimpleSchool.Models.Opleiding", b =>
                {
                    b.Navigation("Leerlingen");
                });

            modelBuilder.Entity("SimpleSchool.Models.StudentenKaart", b =>
                {
                    b.Navigation("Leerling")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
